# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='course_admin.Course'),
        ),
    ]
